<?php

/**
 * Part of Omega - Security Package.
 *
 * @link      https://omegamvc.github.io
 * @author    Adriano Giovannini <agisoftt@gmail.com>
 * @copyright Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version   2.0.0
 */

declare(strict_types=1);

namespace Omega\Security;

use Random\RandomException;

/**
 * Security helper functions for simplified encryption and decryption.
 *
 * These helpers provide a clean and convenient functional interface to the `Crypt`
 * class, allowing data to be encrypted or decrypted without the need to manually
 * instantiate any objects. They support custom pass phrases and configurable
 * encryption algorithms, offering a flexible and secure approach to handling
 * sensitive information throughout the application.
 *
 * @category  Omega
 * @package   Security
 * @link      https://omegamvc.github.io
 * @author    Adriano Giovannini <agisoftt@gmail.com>
 * @copyright Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version   2.0.0
 */

if (!function_exists('encrypt')) {
    /**
     * Encrypts the given plain text using the specified algorithm and optional pass phrase.
     *
     * This helper provides a convenient shortcut to the Crypt class, allowing encryption
     * without manually instantiating Crypt. If no pass phrase is provided, the underlying
     * Crypt implementation will generate or handle a default key as needed.
     *
     * @param string      $plain_text  The raw text that will be encrypted.
     * @param string|null $pass_phrase Optional pass phrase used to derive or provide the encryption key.
     * @param string      $algo        The encryption algorithm identifier (e.g., Algo::AES_256_CBC).
     * @return string The encrypted and encoded string output.
     * @throws RandomException If the encryption process requires secure randomness
     *                         and the system fails to generate it.
     */
    function encrypt(string $plain_text, ?string $pass_phrase = null, string $algo = Algo::AES_256_CBC): string
    {
        return new Crypt($pass_phrase, $algo)->encrypt($plain_text);
    }
}

if (!function_exists('decrypt')) {
    /**
     * Decrypts a previously encrypted string using the specified algorithm and optional pass phrase.
     *
     * This helper acts as a simple wrapper around the Crypt class, making decryption easier
     * by avoiding manual object construction. The same pass phrase and algorithm used during
     * encryption must be provided to successfully restore the original plain text.
     *
     * @param string      $encrypted   The ciphertext generated by the encrypt() helper or Crypt class.
     * @param string|null $pass_phrase The pass phrase used during encryption. If incorrect or missing,
     *                                 decryption will fail.
     * @param string      $algo        The encryption algorithm identifier (e.g., Algo::AES_256_CBC).
     * @return string The decrypted plain text.
     * @throws RandomException If secure randomness is required during the decryption process
     *                         and cannot be obtained from the system.
     */
    function decrypt(string $encrypted, ?string $pass_phrase = null, string $algo = Algo::AES_256_CBC): string
    {
        return new Crypt($pass_phrase, $algo)->decrypt($encrypted);
    }
}
