<?php

/**
 * Part of Omega - Http Package.
 *
 * @link      https://omegamvc.github.io
 * @author    Adriano Giovannini <agisoftt@gmail.com>
 * @copyright Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version   2.0.0
 */

declare(strict_types=1);

namespace Omega\Http\Upload;

use function copy;
use function file_exists;
use function in_array;
use function mkdir;
use function move_uploaded_file;
use function uniqid;
use function unlink;

/**
 * Base abstraction for handling file uploads.
 *
 * This class provides common functionality for uploading files to the server
 * using the native `move_uploaded_file()` function, with optional test mode
 * support via `copy()`.
 *
 * It handles validation rules such as file size limits, allowed extensions,
 * MIME types, and supports both single and multiple file uploads.
 *
 * Concrete implementations are responsible for configuring upload behavior
 * (destination path, file name, allowed types, etc.) through the provided
 * abstract setter methods.
 *
 * @category   Omega
 * @package    Http
 * @subpackage Uploads
 * @link       https://omegamvc.github.io
 * @author     Adriano Giovannini <agisoftt@gmail.com>
 * @copyright  Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license    https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version    2.0.0
 */
abstract class AbstractUpload
{
    /**
     * Raw uploaded file data, usually derived from the $_FILES superglobal.
     *
     * @var array<string, string|array<int, string>>
     */
    protected array $files;

    /** @var bool Indicates whether the upload process completed successfully. */
    protected bool $success = false;

    /** @var bool Indicates whether the upload process has been executed. */
    protected bool $isset = false;

    /**
     * Enables test mode.
     *
     * When enabled, files are copied using `copy()` instead of being moved
     * with `move_uploaded_file()`.
     *
     * @var bool
     */
    protected bool $test = false;

    /** @var bool Indicates whether the upload handles multiple files. */
    protected bool $isMulti = false;

    /** @var string[] Original uploaded file names. */
    protected array $fileName;

    /** @var string[] Original uploaded file MIME types. */
    protected array $fileType;

    /** @var string[] Temporary file paths provided by PHP during upload. */
    protected array $fileTmp;

    /** @var int[] Upload error codes associated with each file. */
    protected array $fileError;

    /** @var int[] Uploaded file sizes in bytes. */
    protected array $fileSize;

    /** @var string[] File extensions extracted from uploaded file names. */
    protected array $fileExtension;

    /** @var string Base name used when saving uploaded files (without extension). */
    protected string $uploadName;

    /** @var string Destination directory where uploaded files will be stored. */
    protected string $uploadLocation = '/';

    /** @var array<int, string> List of allowed file extensions. */
    protected array $uploadTypes = ['jpg', 'jpeg', 'png'];

    /** @var array<int, string> List of allowed MIME types. */
    protected array $uploadMime = ['image/jpg', 'image/jpeg', 'image/png'];

    /** @var int Maximum allowed file size in bytes. */
    protected int $uploadSizeMax = 50000;

    /** @var string Human-readable error message describing the last upload failure. */
    protected string $errorMessage = '';

    /**
     * Create a new upload handler instance.
     *
     * Initializes the upload context using the provided file data,
     * typically coming from the PHP $_FILES superglobal.
     * A random upload name is generated by default.
     *
     * @param array<string, string|int|array<string>|array<int>> $files
     *        Uploaded file data, usually a single entry from $_FILES.
     */
    public function __construct(array $files)
    {
        // random files name by default
        $this->uploadName = uniqid('uploaded_'); // files name without extension

        $this->files = $files;
    }

    /**
     * Determine whether the upload process completed successfully.
     *
     * @return bool True if the file upload succeeded, false otherwise.
     */
    public function success(): bool
    {
        return $this->success;
    }

    /**
     * Get the error message produced during the last upload attempt.
     *
     * @return string A human-readable error message, or an empty string on success.
     */
    public function getError(): string
    {
        return $this->errorMessage;
    }

    /**
     * Get the list of allowed file extensions for upload.
     *
     * @return array<int, string> List of permitted file extensions.
     */
    public function getFileTypes(): array
    {
        return $this->uploadTypes;
    }

    /**
     * Validate uploaded files against configured rules.
     *
     * This method performs the following checks:
     * - Upload error codes
     * - Allowed file extensions
     * - Allowed MIME types
     * - Maximum file size
     *
     * If validation fails, an appropriate error message is set.
     *
     * @return bool True if validation passes, false otherwise.
     */
    protected function validate(): bool
    {
        // check file error
        foreach ($this->fileError as $error) {
            $fileError = $error === 4;
            if ($fileError) {
                $this->errorMessage = 'no file upload';

                return false;
            }
        }

        // check file type (upload_type must set)
        foreach ($this->fileExtension as $extension) {
            $extensionError = !in_array($extension, $this->uploadTypes);
            if ($extensionError) {
                $this->errorMessage = 'file type not support';

                return false;
            }
        }

        // check mime type (upload_mime must set)
        foreach ($this->fileType as $type) {
            $mimeError = !in_array($type, $this->uploadMime);
            if ($mimeError) {
                $this->errorMessage = 'file type not support';

                return false;
            }
        }

        // check file size
        foreach ($this->fileSize as $size) {
            $isSizeError = $size > $this->uploadSizeMax;
            if ($isSizeError) {
                $this->errorMessage = 'file size too large';

                return false;
            }
        }

        $this->errorMessage = 'success';

        return true;
    }

    /**
     * Persist uploaded files to the destination directory.
     *
     * Files are moved using `move_uploaded_file()` by default.
     * When test mode is enabled, files are copied instead.
     *
     * @return string[] List of destination file paths for successfully uploaded files.
     *                  Returns an empty array if validation fails.
     */
    protected function stream(): array
    {
        // isset property, enable when data has been validated
        $this->isset = true;
        $destinations = [];

        if (!$this->validate()) {
            return $destinations;
        }

        if ($this->test) {
            foreach ($this->fileExtension as $key => $extension) {
                $suffix        = $this->isMulti ? $key : '';
                $destination   = $this->uploadLocation . $this->uploadName . $suffix . '.' . $extension;
                $this->success = copy($this->fileTmp[$key], $destination);

                $destinations[] = $destination;
            }

            return $destinations;
        }

        if ($this->test === false) {
            foreach ($this->fileExtension as $key => $extension) {
                $suffix        = $this->isMulti ? $key : '';
                $destination   = $this->uploadLocation . $this->uploadName . $suffix . '.' . $extension;
                $this->success = move_uploaded_file($this->fileTmp[$key], $destination);

                $destinations[] = $destination;
            }

            return $destinations;
        }
    }

    /**
     * Delete a file from the filesystem.
     *
     * @param string $url Absolute or relative path to the file.
     * @return bool True if the file was deleted successfully, false otherwise.
     */
    public function delete(string $url): bool
    {
        /** @noinspection PhpTernaryExpressionCanBeReplacedWithConditionInspection */
        return file_exists($url)
            ? unlink($url)
            : false;
    }

    /**
     * Create a directory recursively if it does not already exist.
     *
     * @param string $path Directory path to create.
     * @return bool True if the directory was created successfully, false otherwise.
     */
    public function creatFolder(string $path): bool
    {
        return !file_exists($path) && mkdir($path, 0777, true);
    }

    /**
     * Set the base file name (without extension).
     *
     * The provided name will be normalized to a URL-safe string
     * before being used for the uploaded file.
     *
     * @param string $fileName Base file name without extension.
     * @return self Fluent interface.
     */
    abstract public function setFileName(string $fileName): self;

    /**
     * Set the destination directory for uploaded files.
     *
     * Note: this method does not create the directory if it does not exist.
     *
     * @param string $folderLocation Absolute or relative upload directory path.
     * @return self Fluent interface.
     */
    abstract public function setFolderLocation(string $folderLocation): self;

    /**
     * Define the list of allowed file extensions.
     *
     * @param array<int, string> $extensions List of permitted file extensions.
     * @return self Fluent interface.
     */
    abstract public function setFileTypes(array $extensions): self;

    /**
     * Define the list of allowed MIME types.
     *
     * @param array<int, string> $mimes List of permitted MIME types.
     * @return self Fluent interface.
     */
    abstract public function setMimeTypes(array $mimes): self;

    /**
     * Set the maximum allowed file size.
     *
     * @param int $byte Maximum file size in bytes.
     * @return self Fluent interface.
     */
    abstract public function setMaxFileSize(int $byte): self;

    /**
     * Enable or disable test mode for file uploads.
     *
     * When enabled, files are copied using `copy()` instead of
     * being moved via `move_uploaded_file()`.
     *
     * @param bool $markUploadTest True to enable test mode.
     * @return self Fluent interface.
     */
    abstract public function markTest(bool $markUploadTest): self;
}
