<?php

/**
 * Part of Omega - Tests\Router Package.
 *
 * @link      https://omegamvc.github.io
 * @author    Adriano Giovannini <agisoftt@gmail.com>
 * @copyright Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license   https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version   2.0.0
 */

declare(strict_types=1);

namespace Tests\Router\Support;

use Omega\Http\Request;
use Omega\Router\RouteDispatcher;
use Omega\Router\Router;
use PHPUnit\Framework\Attributes\CoversClass;

use function call_user_func;
use function call_user_func_array;
use function is_array;
use function ob_get_clean;
use function ob_start;

/**
 * Trait DispatcherTrait
 *
 * Provides a reusable dispatcher method for test classes that need to simulate
 * HTTP requests and route dispatching within the application.
 *
 * This trait allows test cases to:
 *   - Create a fake Request with a given URL and HTTP method.
 *   - Dispatch the request through the application's router.
 *   - Handle found, not found, and method-not-allowed scenarios.
 *   - Capture and return the output generated by the route for assertions.
 *
 * Using this trait eliminates duplication of the dispatcher logic across multiple
 * test classes, while preserving code coverage for the routes and controllers
 * exercised during testing.
 *
 * @category   Tests
 * @package    Router
 * @subpackage Support
 * @link       https://omegamvc.github.io
 * @author     Adriano Giovannini <agisoftt@gmail.com>
 * @copyright  Copyright (c) 2025 Adriano Giovannini (https://omegamvc.github.io)
 * @license    https://www.gnu.org/licenses/gpl-3.0-standalone.html     GPL V3.0+
 * @version    2.0.0
 */
#[CoversClass(Request::class)]
#[CoversClass(RouteDispatcher::class)]
#[CoversClass(Router::class)]
trait DispatcherTrait
{
    /**
     * Simulate a request and dispatch a route.
     *
     * @param string $url The request URI to simulate.
     * @param string $method The HTTP method to simulate.
     * @return false|string Returns the route output or false if the route cannot be dispatched.
     * @noinspection PhpUnusedParameterInspection
     */
    public function dispatcher(string $url, string $method): false|string
    {
        $request  = new Request($url, [], [], [], [], [], [], $method);
        $dispatch = new RouteDispatcher($request, Router::getRoutesRaw());

        $call = $dispatch->run(
        // found
            function ($callable, $param) {
                if (is_array($callable)) {
                    [$class, $method] = $callable;
                    return call_user_func_array([new $class(), $method], $param);
                }
                return call_user_func($callable, $param);
            },
            // not found
            function ($path) {
                echo 'not found';
            },
            // method not allowed
            function ($path, $method) {
                echo 'not allowed';
            }
        );

        ob_start();
        call_user_func_array($call['callable'], $call['params']);

        return ob_get_clean();
    }
}
