#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace App\Http\Middlewares;

use Closure;
use Omega\Http\Request;
use Omega\Http\Response;

class __middleware__Middleware
{
    /**
     * @param Request $request
     * @param Closure $next
     * @return Response
     */
    public function handle(Request $request, Closure $next): Response
    {
        return $next($request);
    }
}
